import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
cwd = GetCurrentDir()

src = Split('''
RISCV/env_Eclipse/handlers.c
RISCV/env_Eclipse/init.c
RISCV/env_Eclipse/your_printf.c
GD32VW55x_standard_peripheral/system_gd32vw55x.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_gpio.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_rcu.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_exti.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_eclic.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_syscfg.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_spi.c']

if GetDepend(['RT_USING_ADC']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_adc.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_timer.c']

if GetDepend(['RT_USING_RTC']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_rtc.c']
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_pmu.c']

if GetDepend(['RT_USING_WDT']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_wwdgt.c']
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_fwdgt.c']

path = [
    cwd + '/RISCV/drivers',
    cwd + '/GD32VW55x_standard_peripheral',
    cwd + '/GD32VW55x_standard_peripheral/Include',]

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
