from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['irq.c']
src += ['irq_port.c']
src += ['sys_clk.c']
src += ['tick.c']
src += ['target_get.c']
src += ['devices.c']

group = DefineGroup('sys', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
