from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['startup.S']
# src += ['vectors.S']
# src += ['system.c']
# src += ['trap_c.c']

group = DefineGroup('startup', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
