from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
CPPPATH += [cwd + '/core']
CPPPATH += [cwd + '/drv']

src =  ['csi_config.h']

group = DefineGroup('asm', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
